Fix TypeError: undefined is not a function in RN 0.65.1
`scrollResponderScrollTo` no longer exists on ScrollResponder in RN 0.65.1, leading to a `TypeError: undefined is not a function` when calling `scrollIntoView`.
This commit fixes this issue by calling `scrollView.scrollTo` instead when `scrollResponderScrollTo` does not exist.